### PR TITLE
move overview and table keys; remove navbar

### PR DESCRIPTION
**Pull request by kweav**
This PR 
1. moves the overview and table keys information from each individual `.Rmd` into a new one: `TableKeys.Rmd`. It also removes the titles from those individual `.Rmd` files. 
2. Removes the navbar from `_site.yml`. Perhaps I should have kept the navbar and changed the title to be an empty string and removed the link to `index.html`. I can make that change if you'd prefer

Next
- Need to widen tables
- Potentially add more info about the category of courses in the overview section here

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks great!Screenshot 2024-05-09 at 5 26 31 PM

**Comment by kweav** [comment]
Awesome -- thank you! Should I go ahead and merge this and see what the website looks like now?

**Comment by carriewright11** [comment]
> Awesome -- thank you! Should I go ahead and merge this and see what the website looks like now?

sorry I always accidentally press enter when I try to make a new line :P I added some more comments about tiny details

**Comment by carriewright11** [comment]
This is looking really good though! I am excited to get feedback from the marketing expert soon

**Comment by kweav** [comment]
> > Awesome -- thank you! Should I go ahead and merge this and see what the website looks like now?
> 
> sorry I always accidentally press enter when I try to make a new line :P I added some more comments about tiny details above

haha no worries!

**Comment by kweav** [comment]
> Looks great!Screenshot 2024-05-09 at 5 26 31 PM
> 
> I had some thoughts about key doc... Maybe we could make the list about different kinds of courses a bulleted list, but I also wonder if we need any of this info as we might want to do it directly on the website? Maybe we just need possibly the blurb about coursera/leanpub for certification onward? Also I noticed that there might be an extra space after the leanpub icon in that first blurb and we might be missing spaces between the the keys (after coursera and leanpub). We could also maybe just add more info about what bookdown, leanpub, and coursera offer in the key explanation to consolidate - I don't think people know what bookdown would mean - so maybe course website is better?

I can work on these -- thanks for pointing them out!

**Pull request merged**
