### PR TITLE
update coursera logo and preview

### PR DESCRIPTION
**Pull request by kweav**
Adjusted the coursera and leanpub logos to use unmodified versions of the logos. Adjusted the size of the leanpub logo to be larger in the table prepping function and in `TableKeys.Rmd`. Leanpub logo now has a white background that I haven't been able to successfully remove. But this is like the Fred Hutch logo so :shrug:

### CODE REVIEW

**Comment by carriewright11** [comment]
I think we could use the leanpub icon that you used previously that didn't have white. I think it is ok to show the other one first with the text - I really like how that looks on the website now. Maybe we can the text "website" , "leanpub", and "source material" to the text column. Idk if it will look funny with the coursera logo, but we can take a look.

**Comment by kweav** [comment]
> I think we could use the leanpub icon that you used previously that didn't have white. I think it is ok to show the other one first with the text - I really like how that looks on the website now. Maybe we can the text "website" , "leanpub", and "source material" to the column. Idk if it will look funny with the coursera logo, but we can take a look.

@carriewright11 Those changes are pushed now

**Comment by carriewright11** [comment]
Looks good! I wonder if we should change the bookdown/website logo to something more recognizable as a website like a curser - maybe this: https://www.iconpacks.net/free-icon/website-9342.html

**Comment by kweav** [comment]
@carriewright11 new commit here changed the relevant links column name to access the course to better communicate those links are the way you're accessing the course

**Comment by carriewright11** [comment]
I think this looks good - let's merge this and talk about other updates based on the feedback we got/will get. I am kinda thinking maybe we should simplify to one table and add another column about category.  I also wonder if we should focus on certification more for leanpub/coursera in the way we display/describe it. I'm very interested in what Mike will say.

**Review by carriewright11 — APPROVED** [review]

**Pull request merged**
