### PR TITLE
Change link color, make logos transparent, and add blurb about certification

### PR DESCRIPTION
**Pull request by kweav**
This PR addresses three open change requests:

1. Change link color to blue from orange (as discussed in #5 code review)
2. Made icons/logos transparent (except for Fred Hutch which removed too much of the edge of the logo)
3. Added a blurb in the overview section for the 3 current course tables saying that completion of coursera and leanpub courses award certification. Phrasing may need edited -- what do you think of it?. 

Next steps (not yet in this PR):
a. Mock up an `About.Rmd` for writers/contributors/who did what
b. Mock up a secret page specific to one course including the images on the website (using ottrpal?), LOs, etc.
c. Finish filling in descriptions for future courses that don't have it
d. incorporate web scraping of information in the input excel file

Any other things you'd like to see next? Or priority list for what's suggested above?

### CODE REVIEW

**Comment by carriewright11** [comment]
> > This PR addresses three open change requests:
> > 
> > 1. Change link color to blue from orange (as discussed in [stylistic updates including rearrange and add icons #5](https://github.com/fhdsl/ITN_course_search/pull/5) code review)
> 
> Looks good!
> 
> > 2. Made icons/logos transparent (except for Fred Hutch which removed too much of the edge of the logo)
> 
> Looks good!
> 
> > 3. Added a blurb in the overview section for the 3 current course tables saying that completion of coursera and leanpub courses award certification. Phrasing may need edited -- what do you think of it?.
>  Maybe it is worth testing embedding as a private page for the ITN site and see if we need to make adjustments
> > Next steps (not yet in this PR):
> 
> > a. Mock up an `About.Rmd` for writers/contributors/who did what
> > Let's do this as the readme (since this will not be shared as it's own website)
> > b. Mock up a secret page specific to one course including the images on the website (using ottrpal?)
> > Maybe we can point to the old version of the course webpage to start? I was thinking maybe we should keep it at least as a hidden page for ourselves, but I am interested to see what you were thinking for this too.
> > LOs, etc.
> > c. Finish filling in descriptions for future courses that don't have it
> > Sounds good!
> 
> > d. incorporate web scraping of information in the input excel file
> > Yup - connecting with Ava would be great!
> 
> > Any other things you'd like to see next? Or priority list for what's suggested above?
> > I think this looks reasonable

**Comment by carriewright11** [comment]
I think there might be an extra space after the coursera logo (at least on the tools and resources courses page - might want to check the others and I am not sure if it is really there)

Screenshot 2024-05-07 at 3 58 20 PM

**Comment by kweav** [comment]
> I think there might be an extra space after the coursera logo (at least on the tools and resources courses page - might want to check the others and I am not sure if it is really there)
> 
> Screenshot 2024-05-07 at 3 58 20 PM

Great catch -- thank you! The logo needed cropped. Should be better now

**Comment by kweav** [comment]
Merging this and going to open a new PR with some of the changes discussed at Lakeside co-working earlier today

**Pull request merged**
