### PR TITLE
update table keys

### PR DESCRIPTION
**Pull request by kweav**
This PR updates the table keys so that 

- link icons and funding icons are on different lines
- the under construction icon is only listed for the future courses table
- the icons themselves are smaller so they don't steal too much attention, but are still visible

The csv file is also updated since I had grabbed some course descriptions for some of the future courses. Need to add more descriptions for the rest of them

### CODE REVIEW

**Comment by kweav** [comment]
Also, updated the overview section to correctly identify which type of table is being displayed. They all said Software Development

**Comment by carriewright11** [comment]
I wonder if we don't need the software developer audience for the table about software development since all of the courses have that audience... unless we add more than one for one of the courses. I realized that this new method allows us to include more than one audience, which is super cool!

(I can't really think of multiple audiences for this particular set of software development courses though)

**Comment by carriewright11** [comment]
But I can think of multiple audiences for the other table courses at times

**Comment by carriewright11** [comment]
> But I can think of multiple audiences for the other table courses at times

LaTeX course could be leaders and new to data for sure, Ethical data handling could be leaders and new to data science, advanced reprod. could be new to data and software development

**Comment by kweav** [comment]
I updated those listed in the google sheet (haven't pushed changes yet), and also added New to data science (in addition to the software developers audience already there) for AI for Efficient Programming. Should AI for Decision Makers only be marked as leaders? From the "For Individuals Who", I would argue yes, but from reading the course too I think it has lessons for those new to data science as well. 

But I was wondering whether it would be useful to add the Concepts discussed as a column?

**Comment by carriewright11** [comment]
> I updated those listed in the google sheet (haven't pushed changes yet), and also added New to data science (in addition to the software developers audience already there) for AI for Efficient Programming. Should AI for Decision Makers only be marked as leaders? From the "For Individuals Who", I would argue yes, but from reading the course too I think it has lessons for those new to data science as well.
> 
> But I was wondering whether it would be useful to add the Concepts discussed as a column?

Sounds good  - that works for me! Yeah, let's try it and see how big it is.

**Comment by carriewright11** [comment]
I merged your dictionary PR

**Comment by carriewright11** [comment]
I think it looks good! It might be nice to see what the concepts look like as bullet points, but I think we can merge this and try that in another PR, what do you think @kweav ?

**Pull request merged**
