### PR TITLE
add for Carrie to see

### PR DESCRIPTION
**Pull request by kweav**

### CODE REVIEW

**Comment by kweav** [comment]
> Broken URLs Note earlier: 

* Fixed the broken URL in `editing.Rmd` in [commit e5c15f5](https://github.com/fhdsl/ITN_course_search/pull/1/commits/e5c15f564ac2b5310ed39c8f76a176d80a4b6107). The link is correct in the OTTR_Template_Website repo, so fixing it here.
* I added spaces between commas and the variables with hyperlinks and that seems to have fixed those being considered "URL errors"

**Comment by carriewright11** [comment]
Looking great!

**Comment by carriewright11** [comment]
> Looking great!
> 
> Some thoughts:
> 
> * [ ]  Could we please remove the icon about being in development from tables for each category of current courses?
> * [ ]  I also think it might help to have a line break between the link icons and the funding icons
> * [ ]  Can we make the funding icons link to info about each?
> * [ ]  Can we remove the description column from future course table - unless we want to add something

This could all be done in new PRs though! (also good to add a description of what each PR is doing :)

**Comment by carriewright11** [comment]
So excited for this!

**Pull request merged**
